#https://hub.docker.com/r/nikolaik/python-nodejs
FROM nikolaik/python-nodejs:python3.11-nodejs20

# Install Flask and Flask-SocketIO
RUN pip install flask flask_socketio google-cloud-speech google-cloud-texttospeech