name: build, test, and dockerize

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Install npm Dependencies
        run: |
          cd talkasaurus-react
          npm install

      - name: Docker Build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: talkasaurusrex:latest