name: "CI/CD Pipeline"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setting up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Get pip cache directory
      id: pip-cache-dir
      run: echo "::set-output name=dir::$(pip cache dir)"

    - name: Set up pip cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.pip-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Server Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt
      
    - name: Set up Node
      uses: actions/setup-node@v2 
      with:
        node-version: '12'

    - name: Setup Cache for Npm
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Client Dependencies
      run: |
        cd ./talkasaurus-react
        npm install

    - name: Tests
      run: echo 'Run application tests.'
      # TODO: Write unit tests and run here.

    - name: Build
      run: echo 'Build application for production.'
      # TODO: Implement steps to build application.

    - name: Deploy
      run: echo 'Deploy application.'
      # TODO: Implement steps to deploy the application.