name: CI/CD Pipeline for TalkasaurusRex

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      
      - name: Install npm dependencies
        run: |
          cd talkasaurus-react
          npm install

      - name: Run client tests
        run: cd talkasaurus-react && npm test

      - name: Run server tests
        run: python -m unittest discover tests

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: talkasaurusrex:latest

      - name: Send Build Notification
        run: echo "Send build notification step goes here"

      - name: Deploy to Production
        run: echo "Deploy step goes here"
        if: github.ref == 'refs/heads/main' # Only run this step on main branch