name: lint

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Python Format Check
      run: |
        pip install flake8
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --show-source --statistics
        pip install black
        black . --check
    - name: JavaScript Check
      run: |
        cd talkasaurus-react
        npm install
        npm run lint

# A feature that can be added to the above workflow is the ability to auto-fix linting errors. 
# This can be achieved by running `--fix` with the lint command and pushing the fixed code back to the repository. 
# However, some like to manually review and fix linting errors.