name: Lint

on: 
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v2
   - name: Set up Python 3.9
     uses: actions/setup-python@v2
     with:
       python-version: 3.9
   - name: Install dependencies
     run: |
       python -m pip install --upgrade pip
       if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
   - name: Pylint
     run: |
       pylint **/*.py
     continue-on-error: true
   - name: ESLint
     uses: wearerequired/lint-action@v1
     with:
       github_token: ${{ secrets.github_token }}
       eslint: true
       eslint_extensions: 'js'
       eslint_args: './talkasaurus-react/src/*'